### ISSUE TITLE
disableClusteringAtZoom breaking zoomToBoundsOnClick

### ISSUE THREAD

**Issue by stephenPickering** [Leaflet/Leaflet.markercluster#648]
Using markerclusterer with **disableClusteringAtZoom** set to 13, some clusters will show the spiderfy circle of markers instead of zooming to the bounds of the cluster members.  This problem goes away if I remove the **disableClusteringAtZoom** option.  I tried specifically setting **zoomToBoundsOnClick** to true just in case the setting was being overridden somehow, but the issue persists.

It seems to happen when the group of markers in a cluster can't be split into smaller clusters.  I have attached examples of what I am seeing.
[Clustering Issue.pdf](https://github.com/Leaflet/Leaflet.markercluster/files/179966/Clustering.Issue.pdf)

**Comment by danzel** [comment]
I'm not opening your pdf.
Please create a live reproduction.

**Comment by stephenPickering** [comment]
Here is a PNG version.  The quality is less than the PDF (didn't think about the possible security issues there, sorry)m but you can still see what is happening.

The site is on a private intranet, so I don't currently have the means to do a reproduction with exact data

![clustering issue](https://cloud.githubusercontent.com/assets/17259650/13986491/b2099d94-f0d0-11e5-840b-a44207c24a8b.png)

.  I can post any any code as is in the page if needed.

**Comment by stephenPickering** [comment]
Sorry, about close/open...laptop fingers.

**Comment by danzel** [comment]
Thanks.
I'm still not 100% certain what is going on from your screenshots, but here is my guess.

I think this is the code that is being hit:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L802-L806

Which means - At the bottom zoom level (13) we think all the markers will still be clustered, so we just spiderfy them rather than zooming down.

I'm not totally sure if what you are seeing is a bug or expected behaviour. If you zoom down further do the markers uncluster?
If so, maybe we shouldn't be using this._maxZoom in that test, but rather look at the maps max zoom or something.

**Comment by ghybs** [comment]
Hi,

Sounds related to #633 and #634.
Except in this very case, as mentioned by danzel, what cluster behaviour do you actually expect?

If you want **no** spiderfication at all (after all, you use `disableClusteringAtZoom` option at a zoom lower than map max zoom, therefore you will always have some zoom levels where your markers will uncluster, without the need to spiderfy), you would be interested in setting [`spiderfyOnMaxZoom` option](https://github.com/Leaflet/Leaflet.markercluster#defaults) to `false`.

And if you do this, you would be interested in PR #634 (either revert PR #609 or modify PR #634 to merge the 2 conditions), so that clicking on a cluster zooms down to cluster bounds in all cases.

Hope this helps.

**Comment by danzel** [comment]
Fixed by #657

**Comment by stephenPickering** [comment]
> what cluster behaviour do you actually expect?

I would expect clicking on a cluster to zoom to the bounds of that cluster at any zoom level outside the disableClusteringAtZoom setting.  One example: 
`disableClusteringAtZoom: 13, zoomToBoundsOnClick: true`
At zoom 13 the points are declustered normally.  At 12 and lower (zooming farther out), the points cluster as they should, but clicking on them does _not_ zoom to the bounds of the cluster, but instead spiderfies the points as in the pictures above. 

The above commit does seem to have affected this behavior.

**Comment by ghybs** [comment]
Hi,

Did it affect the behaviour for the good or bad?

Please not that if you keep `spiderfyOnMaxZoom` option at `true` (as default), you will still see some spiderfication for clusters at zoom 12.

Hope this helps.

**Comment by stephenPickering** [comment]
It doesn't appear to have affected it at all.  The behavior is still the same as the original issue post.  I can post my files (reduced to the offending markers) for you to look at if you can tell me what the best way to get them to you would be.  I'm sure you don't want to be opening strange .zip files.

**Comment by ghybs** [comment]
You are right about the .zip file :-)

Please reproduce your issue on [Plunker](http://plnkr.co/edit/w7b76fEq8namdDuxZf98?p=preview), [JSBin](https://jsbin.com/?html,output) or [JSFiddle](https://jsfiddle.net/yez9wn01/7/).

**Comment by stephenPickering** [comment]
I’ll give it a shot, but I’ll need to do some work first to remove all the references to my linked js files.  I’ll follow up when I get it working.

**Comment by danzel** [comment]
Reopening based on the comments ^^

**Comment by lroal** [comment]
I have the same problem. Is there any work on this issue ?

**Comment by lroal** [comment]
A workaround is to manually listen for clusterclick with zoomToBoundsOnClick = false:

        markers.on('clusterclick', function (a) {
            a.layer.zoomToBounds();
        });

**Comment by ghybs** [comment]
Hi,

Please can you kindly detail what is your issue and which version of Leaflet and markercluster you are using?

It sounds like some people expect a certain behaviour, but it is unclear whether it is just a matter of proper configuration (hence maybe of documentation) or if the plugin behaves counter-intuitively…

Thank you.

**Comment by lroal** [comment]
Versions:
    "leaflet": "^1.0.0-beta.2",
    "leaflet.markercluster": "git@github.com:Leaflet/Leaflet.markercluster.git#v1.0.0-beta.2.0",


var clusterOption = {
    disableClusteringAtZoom: 19,
    zoomToBoundsOnClick: true,
    spiderfyOnMaxZoom: false
};

**Comment by lroal** [comment]
When clicking on a cluster, it doesn't  zoom to bounds. Nothing happens.

**Comment by lroal** [comment]
I have observed the following:
1) If clicking on a cluster at zoomLevel = disableClusteringAtZoom, nothing happens. 
2) If clicking on a cluster at zoomLevel < disableClusteringAtZoom, it zooms into the next "clusterLevel". 

I would expect 1) to zoomToBounds on the markers.

**Comment by lroal** [comment]
This is the source of the problem, if you have reached the lowest level, and spiderFyOnMaxZoom is false, nothing will happen:
[(https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L802-811)]

**Comment by lroal** [comment]
Further digging shows the problem is present in v1.0.0-beta.2.0, but fixed in v1.0.0-rc.1 .
I was running the beta.
Actually, I think this issue should be considered closed now.

**Comment by danzel** [comment]
Alright. If anyone else runs in to this issue, make sure everything is up to date, then make a reproduction case and create a new issue.
Thanks!
